---
- hosts: all
  user: vagrant
  sudo: true

  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - include: tasks/nginx.yml
    - include: tasks/git.yml
    - include: tasks/nodejs.yml
    - include: tasks/npm.yml
    - include: tasks/forever.yml
